- name: Create a xfs filesystem on /dev/sdb
  filesystem:
    fstype: xfs
    dev: /dev/sdb

- name: Mount /var/lib/docker
  mount:
    path: /var/lib/docker
    src: /dev/sdb
    fstype: xfs
    state: mounted

- name: Add docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker
  package:
    name: docker-ce
    state: present

- file:
    name: /etc/docker
    state: directory
    mode: 0755

- name: copy daemon file
  copy:
    src: "{{ files_path }}/daemon.json"
    dest: /etc/docker/daemon.json
    mode: 0644

- name: docker started
  service: name=docker state=started enabled=yes
