- hosts: docker_registry
  roles:
    - ing.docker
    - ing.docker_registry

- hosts: archives
  roles:
    - geerlingguy.nginx
    - ing.archives

- hosts: consul_instances
  roles:
    - ing.consul
    - brianshumate.consul
